# Generated by Django 4.2.5 on 2023-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('date', models.DateField(verbose_name='Дата подачи заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
