# Generated by Django 4.2.5 on 2023-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='descr',
            field=models.CharField(default='Проблема не описана.', max_length=100, verbose_name='Описание проблемы'),
        ),
    ]
