# Generated by Django 4.2.5 on 2023-09-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bid_descr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
        migrations.CreateModel(
            name='BidState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('А', 'Активная'), ('Н', 'Необработанная'), ('З', 'Завершенная')], default='Н', max_length=1, verbose_name='Состояние')),
                ('BidID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.bid')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
