# Generated by Django 4.2.5 on 2023-09-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_bid_options_bidstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='bidstate',
            options={'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
        ),
    ]
